const adminRoutes = {
  "POST /event/": "EventController.create",
  "PUT /event/:id": "EventController.updateEvent",
  "GET /event/:id/users": "EventController.getEventUsers",
  "DELETE /event/:id": "EventController.remove",
  "PUT /event/send-message/:id": "EventController.sendMessageToParticipants",
  "PUT /event/send-test-message/:id": "EventController.sendTestMessage",
  "GET /podcast/:id": "PodcastController.get",
  "POST /podcast/": "PodcastController.add",
  "PUT /podcast/:id": "PodcastController.update",
  "DELETE /podcast/:id": "PodcastController.remove",
  "GET /marketplace/:id": "MarketPlaceController.get",
  "POST /marketplace/": "MarketPlaceController.add",
  "PUT /marketplace/:id": "MarketPlaceController.update",
  "DELETE /marketplace/:id": "MarketPlaceController.remove",
  "GET /marketplace-categories/:id": "MarketplaceCategoriesController.get",
  "POST /marketplace-categories/": "MarketplaceCategoriesController.add",
  "PUT /marketplace-categories/:id": "MarketplaceCategoriesController.update",
  "DELETE /marketplace-categories/:id":
    "MarketplaceCategoriesController.remove",
  "GET /library/all/": "LibraryController.getAll",
  "POST /library/": "LibraryController.create",
  "PUT /library/:id": "LibraryController.update",
  "PUT /library/approve/:id": "LibraryController.approve",
  "PUT /library/reject/:id": "LibraryController.reject",
  "PUT /library/recommend/:id": "LibraryController.recommend",
  "POST /category": "CategoryController.create",
  "PUT /category/:id": "CategoryController.update",
  "DELETE /category/:id": "CategoryController.remove",
  "GET /user/all": "UserController.getAll",
  "GET /conference/:id/": "ConferenceController.get",
  "POST /conference/": "ConferenceController.create",
  "PUT /conference/:id": "ConferenceController.update",
  "DELETE /conference/:id": "ConferenceController.remove",
  "POST /channel-category": "ChannelCategoryController.create",
  "PUT /channel-category/:id": "ChannelCategoryController.update",
  "DELETE /channel-category/:id": "ChannelCategoryController.remove",
  "GET /courses/": "CourseController.getAllAdmin",
  "GET /course/:id": "CourseController.get",
  "POST /course/": "CourseController.add",
  "PUT /course/:id": "CourseController.update",
  "DELETE /course/:id": "CourseController.remove",
  "POST /course-classes/": "CourseClassController.add",
  "PUT /course-classes/:id": "CourseClassController.update",
  "DELETE /course-classes/:id": "CourseClassController.remove",
  "GET /sponsors/": "SponsorController.getAll",
  "GET /sponsor/:id": "SponsorController.get",
  "POST /sponsor/": "SponsorController.add",
  "PUT /sponsor/:id": "SponsorController.update",
  "DELETE /sponsor/:id": "SponsorController.remove",
  "GET /instructors/": "InstructorController.getAll",
  "GET /instructor/:id": "InstructorController.get",
  "POST /instructor/": "InstructorController.add",
  "PUT /instructor/:id": "InstructorController.update",
  "DELETE /instructor/:id": "InstructorController.remove",
};

module.exports = adminRoutes;
