module.exports = {
  NEW_EVENT: "new-event",
  LIVE_CHANGE: "live-change",
  SEND_MESSAGE_GLOBAL_CONFERENCE: "SEND_MESSAGE_GLOBAL_CONFERENCE",
  UPDATE_COUNCIL_EVENT_PANEL: "UPDATE_COUNCIL_EVENT_PANEL",
};
